version: '3.8'

services:
  # قاعدة البيانات PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: wifi-postgres
    environment:
      POSTGRES_DB: wifi_network_db
      POSTGRES_USER: wifi_user
      POSTGRES_PASSWORD: wifi_password_2024
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - wifi-network
    restart: unless-stopped

  # Redis للتخزين المؤقت
  redis:
    image: redis:7-alpine
    container_name: wifi-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - wifi-network
    restart: unless-stopped
    command: redis-server --appendonly yes

  # الواجهة الخلفية
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: wifi-backend
    environment:
      - SECRET_KEY=your-super-secret-key-change-in-production-2024
      - JWT_SECRET_KEY=your-jwt-secret-key-change-in-production-2024
      - DATABASE_URL=postgresql://wifi_user:wifi_password_2024@postgres:5432/wifi_network_db
      - REDIS_URL=redis://redis:6379/0
      - FLASK_ENV=production
      - PORT=5000
    ports:
      - "5000:5000"
    depends_on:
      - postgres
      - redis
    networks:
      - wifi-network
    restart: unless-stopped
    volumes:
      - ./backend/uploads:/app/uploads

  # الواجهة الأمامية
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: wifi-frontend
    environment:
      - VITE_API_BASE_URL=http://localhost:5000/api
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - wifi-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  wifi-network:
    driver: bridge

